---
- name: Create Devpi User
  user:
    name: devpi
    state: present
    system: yes
    home: "{{ devpi_home }}"
    createhome: yes

- name: Create Devpi Data and Config Directory
  file:
    path: "{{ item }}"
    state: directory
    owner: devpi
    group: devpi
    mode: 0755
  with_items:
    - "{{ devpi_data_dir }}"
    - "{{ devpi_config_dir }}"

- name: Create VirtualEnv for Devpi
  become_user: "{{ devpi_user }}"
  command:
    cmd: "virtualenv {{ devpi_venv_dir }}"
    creates: "{{ devpi_venv_dir }}"

- name: Install Devpi Server
  become_user: "{{ devpi_user }}"
  pip:
    name: "{{ item }}"
    virtualenv: "{{ devpi_venv_dir }}"
    state: present
  with_items:
    - "{{ devpi_server_package }}"
    - "{{ devpi_client_package }}"
    - "{{ devpi_web_package }}"

- name: Init Devpi Server
  become_user: "{{ devpi_user }}"
  command:
    cmd: "{{ devpi_venv_dir }}/bin/devpi-init {{ devpi_init_params | join(' ') }}"
    creates: "{{ devpi_data_dir }}/.nodeinfo"

- name: Add Devpi Service
  template:
    src: devpi-server.service.j2
    dest: /etc/systemd/system/devpi-server.service
    owner: root
    group: root
    mode: 0644
  notify: 
    - Reload Systemd
    - Restart Devpi Server

